[theme]
primaryColor = "#004ac6"
backgroundColor = "#f7f9fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#191c1e"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showErrorDetails = true
toolbarMode = "minimal"
